### ISSUE TITLE
Bug on Linea mainnet

### ISSUE THREAD

**Issue by Ali3447** [KyberNetwork/kyberswap-interface#2098]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**
1. Go to ...
2. Click on ...
...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by namgold** [comment]
Please help provide more details, else we can't understand what is the issue here.

**Comment by Ali3447** [comment]
I was doing transactions on the exchange when suddenly the page was out of reach and I had to refresh it and reconnect, and because I was worried, I disconnected the wallet. This happened to me with Ios. I haven't tried it with other devices to see if it happens again.
