### ISSUE TITLE
Cannot yarn install due to @kybernetwork/oauth2 being error 404

### ISSUE THREAD

**Issue by monkins1010** [KyberNetwork/kyberswap-interface#2230]
**Bug Description**
Cannot yarn install due to @kybernetwork/oauth2 being error 404

**Steps to Reproduce**
yarn install

`Error`
```error An unexpected error occurred: "https://npm.pkg.github.com/download/@kybernetwork/oauth2/1.0.0/dbb42e967c8a6755bb801b2c528064764534d00e: Request failed \"401 Unauthorized\"".```

**Expected Behavior**
it installs

**Comment by mylovestar** [comment]
I got same ERROR.
monkins1010, did you fix it?

**Comment by viet-nv** [comment]
Please pull the latest code.
